# -*- makefile-gmake -*-
# $Id: Makefile.flat_tuneups 337652 2011-09-14 13:46:40Z ucko $

all: ptb_all

ifeq "" "$(builddir)$(SKIP_PRELIMINARIES)"
  builddir ?= $(CURDIR)

  CREATE_TUNEUPS = $(top_srcdir)/scripts/common/impl/create_flat_tuneups.sh
  auto_flat_tuneups.mk: $(CREATE_TUNEUPS) Makefile.flat
	$<

  DO_MAKE := $(MAKE)
  expendable_dirs =
  spec_bearing_dirs =
  plain_dirs =
  -include auto_flat_tuneups.mk
endif

# Some projects cannot be built in parallel due to sharing object files.
# The build system's locking mechanism keeps attempts to do so from
# interfering with each other, but can introduce delays, so it would be
# best to avoid intra-build contention altogether.  However, make's
# limitations make that easier said than done; the only way to keep it from
# building a pair of targets in parallel is to claim that one depends on
# the other, which is effective but can result in overbuilding and
# potentially introduce bottlenecks in the case of suboptimal ordering.
# (GNU Make's concept of order-only prerequisites is not as useful as it
# sounds, as make still insists on updating those targets, just not on
# updating whatever lists them as OOPs unless it otherwise has cause to.)
#
# To address these issues, the build system takes a two-pronged approach.
# First, the script (scripts/common/impl/make_lock_map.sh) that produces
# the relevant .hints files attempts to sort targets in decreasing order of
# utility, as gauged by frequency as a prerequisite in Makefile.flat.  In
# addition, this makefile includes the hints only when building high-level
# targets corresponding to multiple leaf targets and their prerequisites,
# as a single application or library and its prerequisites should not
# normally have any object files in common.  Those heuristics are somewhat
# crude, but should keep intra-build contention to a minimum while still
# largely avoiding overbuilding and bottlenecks.

ifneq "" "$(filter-out %.dll.real %.exe.real %.lib.real,$(MAKECMDGOALS))"
  -include $(builddir)/build-system/*.hints
endif

ifndef SKIP_PRELIMINARIES
  ORIG_MTARGET := $(MTARGET)
  QUICK_MTARGET = $(ORIG_MTARGET) sources= configurables=configurables.null
  %.dll.real %.exe.real %.lib.real: override MTARGET = $(QUICK_MTARGET)
endif

all_dirs ?= $(expendable_dirs) $(spec_bearing_dirs) $(plain_dirs)

# Lists of directories in any branch which can benefit from the
# aforementioned hints because some of their projects have files in common.

main_hintees = algo/cobalt/demo app/grid/remote_app cgi \
    connect connect/daemons connect/ext dbapi/driver/ctlib/samples \
    dbapi/driver/ftds64/ctlib/samples dbapi/test dbapi/test/driver \
    objmgr/test sample/app/cgi sample/app/cgires

sra_hintees_ = libs/align libs/axf libs/kdb libx/sra libs/sraxf libs/vdb \
    libs/vxf tools/sra-dump tools/sra-load
sra_hintees = $(sra_hintees_:%=sra/sdk/%)

gpipe_hintees_ = action_nodes/src/altloci_load align_db/user_if/AnnotAlignsDb \
    align_db/user_if/GenomeAlignsDb app/action_nodes app/aligndb app/gbench \
    app/gencoll/gc_update_complete_genomes app/gnomon app/remap app/repeats \
    app/validation app/worker_nodes/blast app/worker_nodes/genemark \
    gencoll/src/gcaccess/get_assembly gpinit/src/gui_build_output \
    objects/genomecoll
gpipe_hintees = $(gpipe_hintees_:%=gpipe/%)

internal_hintees_ = asn_cache/lib gench/app/sviewer/seqgraphic gnomon \
    $(gpipe_hintees) portal/backend/HTB pubmedxml/Libs/PubmedServer \
    snp/qa/snp_validate $(sra_hintees) txserver
internal_hintees = $(internal_hintees_:%=internal/%)

potential_hintees = $(main_hintees) $(sra_hintees) $(internal_hintees)
hintees = $(filter $(potential_hintees:%=%/),$(all_dirs))

# all_files.real : $(all_dirs:%=%.files.real) ;
all_files.real : $(hintees:%=%.files.real) ;

ifndef SKIP_PRELIMINARIES
  $(all_dirs:%=%.files): %.files:
	$(MAKE) $(MFLAGS) -f $(MINPUT) $@.real

  ifneq "$(plain_dirs)" ""
    $(plain_dirs:%=%.files.real): %.files.real:
	+cd ./$*; $(MAKE) $(MFLAGS) sources
  endif

  ifneq "$(expendable_dirs)" ""
    $(expendable_dirs:%=%.files.real): %.files.real:
	+-cd ./$*; $(MAKE) $(MFLAGS) sources
  endif

  .PHONY: $(all_dirs:%=%.files) $(all_dirs:%=%.files.real)
endif
