# $Id: Makefile.flat_shims 327980 2011-07-29 18:47:59Z ucko $
# GMAKE += -f Makefile.flat
MAKE = $(GMAKE)

all:
	@echo "Falling back to GNU Make ($(GMAKE))"
	@+$(GMAKE) --version >/dev/null 2>&1
	+$(GMAKE) $(MFLAGS) -f Makefile.flat ptb_all
