#define IDD_PTB_GUI_DIALOG              100
#define IDC_STATIC_TITLE               1000
#define IDC_STATIC_ROOT                1001
#define IDC_EDIT_ROOT                  1002
#define IDC_STATIC_SUBTREE             1003
#define IDC_EDIT_SUBTREE               1004
#define IDC_STATIC_SLN                 1005
#define IDC_EDIT_SLN                   1006
#define IDC_CHECK_DLL                  1007
#define IDC_CHECK_NOPTB                1008
#define IDC_CHECK_EXT                  1009
#define IDC_CHECK_NWT                  1010
#define IDC_STATIC_EXTROOT             1011
#define IDC_EDIT_EXTROOT               1012
#define IDC_STATIC_PROJTAG             1013
#define IDC_EDIT_PROJTAG               1014
#define IDC_STATIC_FRAME               1015
#define IDC_CHECK_VTUNER               1016
#define IDC_CHECK_VTUNED               1017
#define IDC_STATIC_PTBINI2             1018
#define IDC_EDIT_PTBINI2               1019
#define IDC_STATIC_3PARTY              1020
#define IDC_EDIT_3PARTY                1021
#define IDC_STATIC_CNCBI               1022
#define IDC_EDIT_CNCBI                 1023
#define IDC_STATIC_FRAME2              1024
#define IDC_STATIC_FRAME3              1025
#define IDC_STATIC_VTUNE               1026
