/* $Id: TMgr_Message.cpp 371634 2012-08-09 17:41:42Z clausen $
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 * Author:  .......
 *
 * File Description:
 *   .......
 *
 * Remark:
 *   This code was originally generated by application DATATOOL
 *   using the following specifications:
 *   'trackmgr.asn'.
 */

#include <ncbi_pch.hpp>
#include <objects/trackmgr/TMgr_Message.hpp>

BEGIN_NCBI_SCOPE
BEGIN_objects_SCOPE


CTMgr_Message::CTMgr_Message(TLevel level)
{
    SetLevel(level);
}


CTMgr_Message::CTMgr_Message(TLevel level, const TMessage& message)
{
    SetLevel(level);
    SetMessage(message);
}


CTMgr_Message::~CTMgr_Message(void)
{
}


END_objects_SCOPE
END_NCBI_SCOPE

