/* $Id: FormatRpsDbParameters.hpp 159440 2009-05-05 20:16:38Z camacho $
 * ===========================================================================
 *
 *                            PUBLIC DOMAIN NOTICE
 *               National Center for Biotechnology Information
 *
 *  This software/database is a "United States Government Work" under the
 *  terms of the United States Copyright Act.  It was written as part of
 *  the author's official duties as a United States Government employee and
 *  thus cannot be copyrighted.  This software/database is freely available
 *  to the public for use. The National Library of Medicine and the U.S.
 *  Government have not placed any restriction on its use or reproduction.
 *
 *  Although all reasonable efforts have been taken to ensure the accuracy
 *  and reliability of the software and data, the NLM and the U.S.
 *  Government do not and cannot warrant the performance or results that
 *  may be obtained by using this software or data. The NLM and the U.S.
 *  Government disclaim all warranties, express or implied, including
 *  warranties of performance, merchantability or fitness for any particular
 *  purpose.
 *
 *  Please cite the author in any work or product based on this material.
 *
 * ===========================================================================
 *
 */

/// @file FormatRpsDbParameters.hpp
/// User-defined methods of the data storage class.
///
/// This file was originally generated by application DATATOOL
/// using the following specifications:
/// 'scoremat.asn'.
///
/// New methods or data members can be added to it if needed.
/// See also: FormatRpsDbParameters_.hpp


#ifndef OBJECTS_SCOREMAT_FORMATRPSDBPARAMETERS_HPP
#define OBJECTS_SCOREMAT_FORMATRPSDBPARAMETERS_HPP


// generated includes
#include <objects/scoremat/FormatRpsDbParameters_.hpp>

// generated classes

BEGIN_NCBI_SCOPE

BEGIN_objects_SCOPE // namespace ncbi::objects::

/////////////////////////////////////////////////////////////////////////////
class NCBI_SCOREMAT_EXPORT CFormatRpsDbParameters : public CFormatRpsDbParameters_Base
{
    typedef CFormatRpsDbParameters_Base Tparent;
public:
    // constructor
    CFormatRpsDbParameters(void);
    // destructor
    ~CFormatRpsDbParameters(void);

    bool operator==(const CFormatRpsDbParameters& rhs) const;
    bool operator!=(const CFormatRpsDbParameters& rhs) const;

private:
    // Prohibit copy constructor and assignment operator
    CFormatRpsDbParameters(const CFormatRpsDbParameters& value);
    CFormatRpsDbParameters& operator=(const CFormatRpsDbParameters& value);

};

/////////////////// CFormatRpsDbParameters inline methods

// constructor
inline
CFormatRpsDbParameters::CFormatRpsDbParameters(void)
{
}


/////////////////// end of CFormatRpsDbParameters inline methods


END_objects_SCOPE // namespace ncbi::objects::

END_NCBI_SCOPE


#endif // OBJECTS_SCOREMAT_FORMATRPSDBPARAMETERS_HPP
/* Original file checksum: lines: 86, chars: 2650, CRC32: 4d70eb84 */
