# $Id
##################################

include $(builddir)/Makefile.mk

SCRIPT_NAME = legacy_blast.pl

all:
	@if [ '$(BINCOPY)' != '@:' -a -d $(bindir) -a -w $(bindir) -a $(srcdir) != . ]; then \
	        echo $(BINCOPY) $(srcdir)/$(SCRIPT_NAME) $(bindir) && \
	        $(BINCOPY) $(srcdir)/$(SCRIPT_NAME) $(bindir) || exit $? ; \
	fi

purge:
	-$(RM) $(bindir)/$(SCRIPT_NAME)

clean:

